all:
	g++ -idirafter ../lib/leda/incl functions.h types.h debug.cpp eppstein.cpp single.cpp baseline.cpp max_max.cpp max_sum.cpp max_avg.cpp max_min.cpp max_conn.cpp max_rel.cpp main.cpp -std=c++11 -o colrel.out -L../lib/leda/linux -lleda
